---
stages:
  - build

variables:
  GOPATH: /go
  APP_PATH: /go/src/0xacab.org/leap/bitmask-systray

build_test:
  image: 0xacab.org:4567/leap/bitmask-dev:latest
  stage: build
  script:
    - apt-get -y update
    - apt-get -y install libappindicator3-dev libgtk-3-dev libzmq3-dev golang
    - mkdir -p /go/src/0xacab.org/leap/
    - ln -s "$(pwd)" ${APP_PATH}
    - cd ${APP_PATH}
    - go get .
    - go test ./...
    - make build
  tags:
    - linux
  artifacts:
    paths:
      - 'bitmask-systray'
    expire_in: 1 month
