---
stages:
  - build

variables:
  GOPATH: /go
  APP_PATH: /go/src/0xacab.org/leap/bitmask-systray

build_test:
  image: 0xacab.org:4567/leap/bitmask-dev:latest
  stage: build
  script:
    - apt-get -y update
    - apt-get -y install libappindicator3-dev libgtk-3-dev libzmq3-dev golang
    - mkdir -p /go/src/0xacab.org/leap/
    - ln -s "$(pwd)" ${APP_PATH}
    - cd ${APP_PATH}
    - make get
    - make standalone
    - make build
  tags:
    - linux
  artifacts:
    paths:
      - 'bitmask-systray'
    expire_in: 1 month

win_installer:
 image: 0xacab.org:4567/leap/bitmask-dev:latest
 stage: build
 script:
   - apt-get -y update
   - apt-get -y install mingw-w64 golang upx-ucl

   # we need nsis >= 3.0
   - echo 'deb http://archive.ubuntu.com/ubuntu cosmic universe' >> /etc/apt/sources.list
   - apt-get -y update
   - apt-get -t cosmic -y install nsis

   - mkdir -p /go/src/0xacab.org/leap/
   - ln -s "$(pwd)" ${APP_PATH}
   - cd ${APP_PATH}

   # we need to manually patch w32 until they merge #81
   - mkdir -p /go/src/github.com/AllenDang/
   - cd /go/src/github.com/AllenDang/
   - git clone https://github.com/AllenDang/w32
   - cd w32
   - curl https://downloads.leap.se/thirdparty/w32.patch | patch -p1 -N
   - cd ${APP_PATH}

   - git clone https://0xacab.org/leap/riseup_vpn
   - cd riseup_vpn
   - make openvpn_cross_win
   - make build_cross_win
   - mv dist/RiseupVPN-*.exe ..
 tags:
   - linux
 artifacts:
   name: installer_win_$CI_COMMIT_REF_NAME
   paths:
     - RiseupVPN-*.exe
   expire_in: 1 month

snap:
 image: 0xacab.org:4567/leap/bitmask-dev:latest
 stage: build
 script:
   - apt-get -y update
   - apt-get -y install snapcraft

   - mkdir -p /go/src/0xacab.org/leap/
   - ln -s "$(pwd)" ${APP_PATH}
   - cd ${APP_PATH}

   - git clone https://0xacab.org/leap/riseup_vpn
   - cd riseup_vpn
   - snapcraft build
   - snapcraft snap
   - mv riseup-vpn*.snap ..
 tags:
   - linux
 artifacts:
   name: snap_$CI_COMMIT_REF_NAME
   paths:
     - riseup-vpn*.snap
   expire_in: 1 month
